name: ci-acme

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2  
    - name: bootstrap 
      run:  make bootstrap with=docker
    - name: lint 
      run:  make lint with=docker
    - name: test 
      run:  make test with=docker
